"""create foundation authority schema

Revision ID: 8d1fc3598816
Revises:
Create Date: 2026-08-30 18:09:43.401952
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8d1fc3598816"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("actor_subject", sa.String(length=180), nullable=False),
        sa.Column("action", sa.String(length=180), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=180), nullable=False),
        sa.Column("detail_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_tenant_time", "audit_events", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=180), nullable=False),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "operation", "idempotency_key", name="uq_idempotency_scope"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=180), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.String(length=180), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('PENDING','SENDING','DELIVERED','DEAD_LETTER')", name="ck_outbox_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_outbox_pending", "outbox_events", ["status", "created_at"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED','CLOSED')", name="ck_tenant_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "billing_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_tenant_id", sa.String(length=36), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_day", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("tax_profile_enc", sa.Text(), nullable=False),
        sa.Column("external_customer_ref", sa.String(length=180), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE','PAST_DUE','CLOSED')", name="ck_billing_account_status"),
        sa.CheckConstraint("billing_day BETWEEN 1 AND 28", name="ck_billing_day"),
        sa.ForeignKeyConstraint(
            ["owner_tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entitlements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("entitlement_key", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("limit_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("limit_value IS NULL OR limit_value >= 0", name="ck_entitlement_nonnegative"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "entitlement_key", name="uq_entitlement_tenant_key"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("external_ref", sa.String(length=180), nullable=True),
        sa.Column("display_name_enc", sa.Text(), nullable=True),
        sa.Column("attributes_enc", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("merged_into_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name="ck_profile_version"),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "external_ref", name="uq_profile_tenant_external_ref"),
    )
    op.create_table(
        "consent_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=True),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("lawful_basis", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_subject", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("channel IN ('ALL','EMAIL','SMS','VOICE','SOCIAL')", name="ck_consent_channel"),
        sa.CheckConstraint("state IN ('GRANTED','DENIED','REVOKED')", name="ck_consent_state"),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_consent_effective",
        "consent_events",
        ["tenant_id", "identity_hash", "topic", "channel", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value_hash", sa.String(length=64), nullable=False),
        sa.Column("value_enc", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('EMAIL','PHONE','EXTERNAL')", name="ck_identity_kind"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "kind", "value_hash", name="uq_identity_tenant_kind_hash"),
    )
    op.create_index("ix_identity_lookup", "identities", ["tenant_id", "kind", "value_hash"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("credit_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_PAYMENT','ACTION_REQUIRED','PAID','PAST_DUE','REFUNDED','VOID')",
            name="ck_invoice_status",
        ),
        sa.CheckConstraint("total_amount >= 0", name="ck_invoice_total_nonnegative"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["billing_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "period_end", name="uq_invoice_account_period_end"),
    )
    op.create_table(
        "preferences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=True),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("frequency", sa.String(length=40), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("channel IN ('ALL','EMAIL','SMS','VOICE','SOCIAL')", name="ck_preference_channel"),
        sa.CheckConstraint("state IN ('SUBSCRIBED','UNSUBSCRIBED')", name="ck_preference_state"),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "identity_hash", "topic", "channel", name="uq_preference_effective"),
    )
    op.create_table(
        "profile_merges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("source_profile_id", sa.String(length=36), nullable=False),
        sa.Column("target_profile_id", sa.String(length=36), nullable=False),
        sa.Column("actor_subject", sa.String(length=180), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_profile_id", name="uq_profile_merge_source"),
    )
    op.create_table(
        "suite_subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("suite_code", sa.String(length=80), nullable=False),
        sa.Column("plan_code", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("quota_behavior", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trial_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quota_behavior IN ('OVERAGE','BLOCK','AUTO_UPGRADE')", name="ck_quota_behavior"),
        sa.CheckConstraint(
            "status IN ('TRIALING','ACTIVE','PAST_DUE','SUSPENDED','CANCELLED')", name="ck_subscription_status"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["billing_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "suite_code", name="uq_subscription_tenant_suite"),
    )
    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("invoice_id", sa.String(length=36), nullable=False),
        sa.Column("line_code", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("unit_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("line_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.CheckConstraint("quantity >= 0 AND unit_amount >= 0 AND line_amount >= 0", name="ck_line_nonnegative"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usage_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("subscription_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("suite_code", sa.String(length=80), nullable=False),
        sa.Column("meter_code", sa.String(length=120), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("event_key", sa.String(length=240), nullable=False),
        sa.Column("source_object_id", sa.String(length=180), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_usage_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["billing_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["suite_subscriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "event_key", name="uq_usage_tenant_event_key"),
    )
    op.create_index(
        "ix_usage_period", "usage_events", ["account_id", "suite_code", "meter_code", "occurred_at"], unique=False
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            sa.text(
                """
                CREATE FUNCTION foundation_reject_append_only_mutation()
                RETURNS trigger AS $$
                BEGIN
                  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
                END;
                $$ LANGUAGE plpgsql;
                """
            )
        )
        for table_name in ("audit_events", "consent_events", "usage_events"):
            op.execute(
                sa.text(
                    f"""
                    CREATE TRIGGER {table_name}_append_only
                    BEFORE UPDATE OR DELETE ON {table_name}
                    FOR EACH ROW EXECUTE FUNCTION foundation_reject_append_only_mutation();
                    """
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_period", table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_table("invoice_lines")
    op.drop_table("suite_subscriptions")
    op.drop_table("profile_merges")
    op.drop_table("preferences")
    op.drop_table("invoices")
    op.drop_index("ix_identity_lookup", table_name="identities")
    op.drop_table("identities")
    op.drop_index("ix_consent_effective", table_name="consent_events")
    op.drop_table("consent_events")
    op.drop_table("profiles")
    op.drop_table("entitlements")
    op.drop_table("billing_accounts")
    op.drop_table("tenants")
    op.drop_index("ix_outbox_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("idempotency_records")
    op.drop_index("ix_audit_tenant_time", table_name="audit_events")
    op.drop_table("audit_events")
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("DROP FUNCTION foundation_reject_append_only_mutation()"))
    # ### end Alembic commands ###
